-- 0004：为 CET-4 种子词写入例句（幂等，可重复执行）
UPDATE words SET example = 'She has the ability to solve difficult problems under pressure.', example_zh = '她有在压力下解决难题的能力。' WHERE text = 'ability';
UPDATE words SET example = 'Plants absorb carbon dioxide and release oxygen.', example_zh = '植物吸收二氧化碳并释放氧气。' WHERE text = 'absorb';
UPDATE words SET example = 'The concept of beauty is quite abstract and hard to define.', example_zh = '美这个概念相当抽象，难以定义。' WHERE text = 'abstract';
UPDATE words SET example = 'His academic performance improved greatly this semester.', example_zh = '他这学期的学习成绩进步很大。' WHERE text = 'academic';
UPDATE words SET example = 'She was glad to accept the invitation to the party.', example_zh = '她很高兴接受聚会的邀请。' WHERE text = 'accept';
UPDATE words SET example = 'Her friend will accompany her to the hospital.', example_zh = '她的朋友将陪她去医院。' WHERE text = 'accompany';
UPDATE words SET example = 'The weather forecast is not always accurate.', example_zh = '天气预报并不总是准确的。' WHERE text = 'accurate';
UPDATE words SET example = 'They accuse him of stealing the company secret.', example_zh = '他们指控他窃取了公司的秘密。' WHERE text = 'accuse';
UPDATE words SET example = 'You can achieve your goals through hard work.', example_zh = '通过努力工作你可以实现自己的目标。' WHERE text = 'achieve';
UPDATE words SET example = 'He refused to acknowledge his own mistakes.', example_zh = '他拒绝承认自己的错误。' WHERE text = 'acknowledge';
UPDATE words SET example = 'It takes years to acquire a new language.', example_zh = '掌握一门新语言需要多年时间。' WHERE text = 'acquire';
UPDATE words SET example = 'Animals must adapt to changes in their environment.', example_zh = '动物必须适应环境的变化。' WHERE text = 'adapt';
UPDATE words SET example = 'Make sure you get adequate sleep before the exam.', example_zh = '考试前一定要保证充足的睡眠。' WHERE text = 'adequate';
UPDATE words SET example = 'You can adjust the height of the chair easily.', example_zh = '你可以轻松调整椅子的高度。' WHERE text = 'adjust';
UPDATE words SET example = 'I deeply admire her courage and honesty.', example_zh = '我深深钦佩她的勇气和诚实。' WHERE text = 'admire';
UPDATE words SET example = 'He had to admit that he was wrong.', example_zh = '他不得不承认自己错了。' WHERE text = 'admit';
UPDATE words SET example = 'The family decided to adopt a child from abroad.', example_zh = '这家人决定从国外领养一个孩子。' WHERE text = 'adopt';
UPDATE words SET example = 'Technology continues to advance at a rapid pace.', example_zh = '科技继续快速进步。' WHERE text = 'advance';
UPDATE words SET example = 'Speaking two languages gives you a big advantage.', example_zh = '会说两种语言给你带来很大优势。' WHERE text = 'advantage';
UPDATE words SET example = 'Many teachers advocate less homework and more practice.', example_zh = '许多老师主张少布置作业、多做练习。' WHERE text = 'advocate';
UPDATE words SET example = 'Her ambition is to become a professional doctor.', example_zh = '她的志向是成为一名职业医生。' WHERE text = 'ambition';
UPDATE words SET example = 'He spent a large amount of money on books.', example_zh = '他花了一大笔钱买书。' WHERE text = 'amount';
UPDATE words SET example = 'Scientists analyze the data before drawing conclusions.', example_zh = '科学家在得出结论之前先分析数据。' WHERE text = 'analyze';
UPDATE words SET example = 'They celebrated their tenth wedding anniversary last week.', example_zh = '上周他们庆祝了结婚十周年纪念日。' WHERE text = 'anniversary';
UPDATE words SET example = 'The company will announce its new product tomorrow.', example_zh = '公司明天将发布新产品。' WHERE text = 'announce';
UPDATE words SET example = 'The annual meeting will be held in December.', example_zh = '年会将于十二月举行。' WHERE text = 'annual';
UPDATE words SET example = 'We anticipate that prices will rise next year.', example_zh = '我们预计明年物价会上涨。' WHERE text = 'anticipate';
UPDATE words SET example = 'Exam anxiety is common among students.', example_zh = '考试焦虑在学生中很常见。' WHERE text = 'anxiety';
UPDATE words SET example = 'She felt anxious about the interview results.', example_zh = '她对面试结果感到焦虑。' WHERE text = 'anxious';
UPDATE words SET example = 'You should apologize for being late again.', example_zh = '你应该为再次迟到道歉。' WHERE text = 'apologize';
UPDATE words SET example = 'It was apparent that he knew nothing about the plan.', example_zh = '显然他对这个计划一无所知。' WHERE text = 'apparent';
UPDATE words SET example = 'These pictures appeal to young people.', example_zh = '这些图片很吸引年轻人。' WHERE text = 'appeal';
UPDATE words SET example = 'Exercise gives me a good appetite.', example_zh = '锻炼让我胃口大开。' WHERE text = 'appetite';
UPDATE words SET example = 'Please do not applaud until the performance ends.', example_zh = '演出结束前请不要鼓掌。' WHERE text = 'applaud';
UPDATE words SET example = 'I really appreciate your help with the project.', example_zh = '我非常感谢你在这个项目上的帮助。' WHERE text = 'appreciate';
UPDATE words SET example = 'We need a new approach to solve this problem.', example_zh = '我们需要一个新方法来解决这个问题。' WHERE text = 'approach';
UPDATE words SET example = 'Jeans are not appropriate for a formal dinner.', example_zh = '牛仔裤不适合正式晚宴。' WHERE text = 'appropriate';
UPDATE words SET example = 'Her parents did not approve of her decision.', example_zh = '她的父母不赞成她的决定。' WHERE text = 'approve';
UPDATE words SET example = 'The rules seem completely arbitrary and unfair.', example_zh = '这些规则似乎完全武断且不公平。' WHERE text = 'arbitrary';
UPDATE words SET example = 'Teachers assess student progress every month.', example_zh = '老师们每个月评估学生的进步。' WHERE text = 'assess';
UPDATE words SET example = 'Do not assume that everyone agrees with you.', example_zh = '不要想当然地认为每个人都同意你的看法。' WHERE text = 'assume';
UPDATE words SET example = 'Many people attribute their success to luck rather than effort.', example_zh = '许多人把成功归因于运气而非努力。' WHERE text = 'attribute';
UPDATE words SET example = 'The museum displays authentic ancient coins.', example_zh = '博物馆展出真正的古钱币。' WHERE text = 'authentic';
UPDATE words SET example = 'The region became fully autonomous in 1993.', example_zh = '该地区于1993年完全自治。' WHERE text = 'autonomous';
UPDATE words SET example = 'This test sets the benchmark for high school English.', example_zh = '这项测试为高中英语设定了基准。' WHERE text = 'benchmark';
UPDATE words SET example = 'Regular exercise can benefit both body and mind.', example_zh = '定期锻炼对身心都有益处。' WHERE text = 'benefit';
UPDATE words SET example = 'The report was criticized for its political bias.', example_zh = '该报告因政治偏见而受到批评。' WHERE text = 'bias';
UPDATE words SET example = 'A good night of sleep can boost your memory.', example_zh = '一夜好眠能提升你的记忆力。' WHERE text = 'boost';
UPDATE words SET example = 'The river forms the boundary between the two countries.', example_zh = '这条河构成了两国的边界。' WHERE text = 'boundary';
UPDATE words SET example = 'Scientists made a major breakthrough in cancer research.', example_zh = '科学家在癌症研究方面取得重大突破。' WHERE text = 'breakthrough';
UPDATE words SET example = 'The stadium has a seating capacity of eighty thousand.', example_zh = '这座体育场可容纳八万人就座。' WHERE text = 'capacity';
UPDATE words SET example = 'The company decided to cease production of the old model.', example_zh = '公司决定停止生产旧型号。' WHERE text = 'cease';
UPDATE words SET example = 'Learning a foreign language is a big challenge.', example_zh = '学习外语是一个巨大的挑战。' WHERE text = 'challenge';
UPDATE words SET example = 'We cannot control every circumstance in life.', example_zh = '我们无法控制生活中的每一种情况。' WHERE text = 'circumstance';
UPDATE words SET example = 'The two universities collaborate on environmental research.', example_zh = '这两所大学在环境研究方面合作。' WHERE text = 'collaborate';
UPDATE words SET example = 'Water has become a precious commodity in dry regions.', example_zh = '在干旱地区，水已成为珍贵的商品。' WHERE text = 'commodity';
UPDATE words SET example = 'This software is not compatible with older phones.', example_zh = '这款软件与旧手机不兼容。' WHERE text = 'compatible';
UPDATE words SET example = 'Nothing can compensate for the loss of time.', example_zh = '什么都无法弥补时间的损失。' WHERE text = 'compensate';
UPDATE words SET example = 'A competent driver knows the traffic rules well.', example_zh = '一名合格的司机非常熟悉交通规则。' WHERE text = 'competent';
UPDATE words SET example = 'The book offers a comprehensive guide to gardening.', example_zh = '这本书提供了全面的园艺指南。' WHERE text = 'comprehensive';
UPDATE words SET example = 'Both sides refused to compromise on the key issue.', example_zh = '双方都拒绝在关键问题上妥协。' WHERE text = 'compromise';
UPDATE words SET example = 'He tried to conceal his disappointment behind a smile.', example_zh = '他试图用微笑掩饰失望。' WHERE text = 'conceal';
UPDATE words SET example = 'It is hard to conceive of life without the Internet.', example_zh = '很难想象没有互联网的生活。' WHERE text = 'conceive';
UPDATE words SET example = 'All countries condemn violence of any kind.', example_zh = '所有国家都谴责任何形式的暴力。' WHERE text = 'condemn';
UPDATE words SET example = 'Please confirm your reservation by phone.', example_zh = '请打电话确认您的预订。' WHERE text = 'confirm';
UPDATE words SET example = 'He lost his job as a consequence of the scandal.', example_zh = '他因这起丑闻而丢了工作。' WHERE text = 'consequence';
UPDATE words SET example = 'My grandfather has very conservative views on education.', example_zh = '我祖父在教育问题上观点非常保守。' WHERE text = 'conservative';
UPDATE words SET example = 'The project requires a considerable amount of time.', example_zh = '这个项目需要相当多的时间。' WHERE text = 'considerable';
UPDATE words SET example = 'His actions contradict his words.', example_zh = '他的言行自相矛盾。' WHERE text = 'contradict';
UPDATE words SET example = 'The new law caused a heated controversy.', example_zh = '新法律引发了激烈的争议。' WHERE text = 'controversy';
UPDATE words SET example = 'The evidence failed to convince the jury.', example_zh = '证据未能说服陪审团。' WHERE text = 'convince';
UPDATE words SET example = 'The two companies cooperate on green energy projects.', example_zh = '这两家公司在绿色能源项目上合作。' WHERE text = 'cooperate';
UPDATE words SET example = 'Price is not the only criterion for choosing a phone.', example_zh = '价格不是选择手机的唯一标准。' WHERE text = 'criterion';
UPDATE words SET example = 'Good communication is crucial to a happy marriage.', example_zh = '良好的沟通对幸福婚姻至关重要。' WHERE text = 'crucial';
UPDATE words SET example = 'Reading helps cultivate the mind.', example_zh = '阅读有助于修养心智。' WHERE text = 'cultivate';
UPDATE words SET example = 'The birth rate continues to decline in many countries.', example_zh = '许多国家的出生率持续下降。' WHERE text = 'decline';
UPDATE words SET example = 'He decided to dedicate his life to medical research.', example_zh = '他决定把一生献给医学研究。' WHERE text = 'dedicate';
UPDATE words SET example = 'The teacher used pictures to demonstrate the idea.', example_zh = '老师用图片演示了这个想法。' WHERE text = 'demonstrate';
UPDATE words SET example = 'Volunteers distribute food to the homeless every weekend.', example_zh = '志愿者每个周末给无家可归者分发食物。' WHERE text = 'distribute';
UPDATE words SET example = 'New York is famous for its diverse culture.', example_zh = '纽约以其多元的文化闻名。' WHERE text = 'diverse';
UPDATE words SET example = 'The national economy grew by three percent this year.', example_zh = '今年国民经济增长了百分之三。' WHERE text = 'economy';
UPDATE words SET example = 'We should eliminate bad habits step by step.', example_zh = '我们应该逐步消除坏习惯。' WHERE text = 'eliminate';
UPDATE words SET example = 'Schools place great emphasis on exam results.', example_zh = '学校非常重视考试成绩。' WHERE text = 'emphasis';
UPDATE words SET example = 'The new software enables faster data processing.', example_zh = '新软件使更快的数据处理成为可能。' WHERE text = 'enable';
UPDATE words SET example = 'Tourists may encounter heavy rain in the mountains.', example_zh = '游客在山区可能遇到大雨。' WHERE text = 'encounter';
UPDATE words SET example = 'Music can enhance your learning experience.', example_zh = '音乐能提升你的学习体验。' WHERE text = 'enhance';
UPDATE words SET example = 'An enormous amount of work remains to be done.', example_zh = '还有大量的工作要做。' WHERE text = 'enormous';
UPDATE words SET example = 'Please ensure that all doors are locked before leaving.', example_zh = '离开前请确保所有门都已锁好。' WHERE text = 'ensure';
UPDATE words SET example = 'They plan to establish a new research center.', example_zh = '他们计划建立一个新的研究中心。' WHERE text = 'establish';
UPDATE words SET example = 'Experts evaluate the safety of new medicines.', example_zh = '专家评估新药的安全性。' WHERE text = 'evaluate';
UPDATE words SET example = 'It was evident that she had practiced a lot.', example_zh = '显然她进行了大量练习。' WHERE text = 'evident';
UPDATE words SET example = 'Companies must evolve to survive fierce competition.', example_zh = '公司必须不断进化才能在激烈竞争中生存。' WHERE text = 'evolve';
UPDATE words SET example = 'Do not exceed the speed limit while driving.', example_zh = '开车时不要超过限速。' WHERE text = 'exceed';
UPDATE words SET example = 'The new app facilitates communication between teachers and parents.', example_zh = '新应用促进了教师与家长之间的沟通。' WHERE text = 'facilitate';
UPDATE words SET example = 'Reading is a fundamental skill for every student.', example_zh = '阅读是每个学生的基本技能。' WHERE text = 'fundamental';
UPDATE words SET example = 'Wind turbines generate clean electricity.', example_zh = '风力涡轮机产生清洁电力。' WHERE text = 'generate';
UPDATE words SET example = 'The experiment supports our original hypothesis.', example_zh = '实验支持了我们最初的假设。' WHERE text = 'hypothesis';
UPDATE words SET example = 'The school will implement new safety rules next term.', example_zh = '学校下学期将实施新的安全规定。' WHERE text = 'implement';
UPDATE words SET example = 'Change is inevitable in a fast-growing city.', example_zh = '在快速发展的城市中，变化是不可避免的。' WHERE text = 'inevitable';
UPDATE words SET example = 'Parents have a strong influence on their children.', example_zh = '父母对孩子有很大影响。' WHERE text = 'influence';
