-- 0008_seed_cet6.sql: 词书「CET-6 进阶词」种子
-- 由 apps/server/scripts/gen-seed-sql.mjs 生成，请勿手改；difficulty 留空由管道懒计算。

INSERT OR REPLACE INTO wordbooks (id, name, level_tag, version, description, min_tier, created_at) VALUES ('cet6', 'CET-6 进阶词', 'CET-6', 1, 'B2-C1 高阶词包：历史最高段位达到「黄金」解锁（段位系统 C10）', 3, '2026-09-14T20:11:14.622Z');

INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('ambiguous', 'ambiguous', '/æmˈbɪɡjuəs/', '[{"pos":"adj.","meaning":"模棱两可的；含糊不清的"}]', NULL, NULL, 'B2', 8800, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('deteriorate', 'deteriorate', '/dɪˈtɪəriəreɪt/', '[{"pos":"vi.","meaning":"恶化，变坏"}]', NULL, NULL, 'C1', 11200, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('elaborate', 'elaborate', '/ɪˈlæbərət/ /ɪˈlæbəreɪt/', '[{"pos":"adj.","meaning":"精心制作的；复杂的"},{"pos":"vi.","meaning":"详述"}]', NULL, NULL, 'C1', 9400, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('feasible', 'feasible', '/ˈfiːzəbl/', '[{"pos":"adj.","meaning":"可行的"}]', NULL, NULL, 'B2', 9200, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('hierarchy', 'hierarchy', '/ˈhaɪərɑːki/', '[{"pos":"n.","meaning":"等级制度；层级"}]', NULL, NULL, 'C1', 9800, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('jurisdiction', 'jurisdiction', '/ˌdʒʊərɪsˈdɪkʃn/', '[{"pos":"n.","meaning":"司法管辖权；管辖范围"}]', NULL, NULL, 'C1', 13000, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('legitimate', 'legitimate', '/lɪˈdʒɪtɪmət/', '[{"pos":"adj.","meaning":"合法的；正当的"}]', NULL, NULL, 'B2', 9000, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('magnitude', 'magnitude', '/ˈmæɡnɪtjuːd/', '[{"pos":"n.","meaning":"巨大；重要性"}]', NULL, NULL, 'C1', 11500, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('magnificent', 'magnificent', '/mæɡˈnɪfɪsnt/', '[{"pos":"adj.","meaning":"壮丽的；宏伟的"}]', NULL, NULL, 'B2', 8200, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('nourish', 'nourish', '/ˈnʌrɪʃ/', '[{"pos":"vt.","meaning":"滋养；培养"}]', NULL, NULL, 'C1', 11600, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('obsolete', 'obsolete', '/ˈɒbsəliːt/', '[{"pos":"adj.","meaning":"过时的；废弃的"}]', NULL, NULL, 'C1', 12200, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('paradox', 'paradox', '/ˈpærədɒks/', '[{"pos":"n.","meaning":"悖论；自相矛盾的事物"}]', NULL, NULL, 'C1', 10600, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('phenomenon', 'phenomenon', '/fəˈnɒmɪnən/', '[{"pos":"n.","meaning":"现象"}]', NULL, NULL, 'B2', 4600, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('preliminary', 'preliminary', '/prɪˈlɪmɪnəri/', '[{"pos":"adj.","meaning":"初步的，预备的"}]', NULL, NULL, 'B2', 9600, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('prosperity', 'prosperity', '/prɒˈsperəti/', '[{"pos":"n.","meaning":"繁荣，兴旺"}]', NULL, NULL, 'B2', 8400, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('reconcile', 'reconcile', '/ˈrekənsaɪl/', '[{"pos":"vt.","meaning":"调和；使和解"}]', NULL, NULL, 'C1', 11000, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('redundant', 'redundant', '/rɪˈdʌndənt/', '[{"pos":"adj.","meaning":"多余的，冗余的"}]', NULL, NULL, 'C1', 12500, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('skeptical', 'skeptical', '/ˈskeptɪkl/', '[{"pos":"adj.","meaning":"怀疑的"}]', NULL, NULL, 'B2', 10000, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('sophisticated', 'sophisticated', '/səˈfɪstɪkeɪtɪd/', '[{"pos":"adj.","meaning":"复杂的；精密的"}]', NULL, NULL, 'B2', 7600, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('subsidiary', 'subsidiary', '/səbˈsɪdiəri/', '[{"pos":"n.","meaning":"子公司"},{"pos":"adj.","meaning":"辅助的；附属的"}]', NULL, NULL, 'C1', 12600, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('substantial', 'substantial', '/səbˈstænʃl/', '[{"pos":"adj.","meaning":"大量的；实质的"}]', NULL, NULL, 'B2', 5600, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('substantiate', 'substantiate', '/səbˈstænʃieɪt/', '[{"pos":"vt.","meaning":"证实"}]', NULL, NULL, 'C1', 14500, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('terminate', 'terminate', '/ˈtɜːmɪneɪt/', '[{"pos":"v.","meaning":"终止；结束"}]', NULL, NULL, 'C1', 11000, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('transient', 'transient', '/ˈtrænziənt/', '[{"pos":"adj.","meaning":"短暂的；转瞬即逝的"}]', NULL, NULL, 'C1', 13200, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('versatile', 'versatile', '/ˈvɜːsətaɪl/', '[{"pos":"adj.","meaning":"多才多艺的；多用途的"}]', NULL, NULL, 'C1', 10600, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('vulnerable', 'vulnerable', '/ˈvʌlnərəbl/', '[{"pos":"adj.","meaning":"脆弱的；易受伤害的"}]', NULL, NULL, 'B2', 6900, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('withstand', 'withstand', '/wɪðˈstænd/', '[{"pos":"vt.","meaning":"承受；经受住"}]', NULL, NULL, 'C1', 12600, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('abolish', 'abolish', '/əˈbɒlɪʃ/', '[{"pos":"vt.","meaning":"废除"}]', NULL, NULL, 'B2', 8500, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('accumulate', 'accumulate', '/əˈkjuːmjəleɪt/', '[{"pos":"vt./vi.","meaning":"积累，积聚"}]', NULL, NULL, 'B2', 7700, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('aggravate', 'aggravate', '/ˈæɡrəveɪt/', '[{"pos":"vt.","meaning":"加剧；使恶化"}]', NULL, NULL, 'C1', 11800, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('alleviate', 'alleviate', '/əˈliːvieɪt/', '[{"pos":"vt.","meaning":"减轻，缓解"}]', NULL, NULL, 'C1', 12200, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('appraisal', 'appraisal', '/əˈpreɪzl/', '[{"pos":"n.","meaning":"评估；估价"}]', NULL, NULL, 'C1', 13500, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('articulate', 'articulate', '/ɑːˈtɪkjuleɪt/；/ɑːˈtɪkjələt/', '[{"pos":"vt.","meaning":"清晰表达"},{"pos":"adj.","meaning":"善于表达的"}]', NULL, NULL, 'C1', 12000, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('aspiration', 'aspiration', '/ˌæspəˈreɪʃn/', '[{"pos":"n.","meaning":"抱负，志向"}]', NULL, NULL, 'C1', 10800, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('assimilate', 'assimilate', '/əˈsɪməleɪt/', '[{"pos":"vt./vi.","meaning":"同化；吸收"}]', NULL, NULL, 'C1', 12800, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('bewilder', 'bewilder', '/bɪˈwɪldə/', '[{"pos":"vt.","meaning":"使迷惑，使困惑"}]', NULL, NULL, 'C1', 13800, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('bureaucracy', 'bureaucracy', '/bjʊəˈrɒkrəsi/', '[{"pos":"n.","meaning":"官僚机构；官僚主义"}]', NULL, NULL, 'C1', 12000, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('coincide', 'coincide', '/ˌkəʊɪnˈsaɪd/', '[{"pos":"vi.","meaning":"同时发生；一致"}]', NULL, NULL, 'C1', 10500, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('coherent', 'coherent', '/kəʊˈhɪərənt/', '[{"pos":"adj.","meaning":"连贯的；条理清晰的"}]', NULL, NULL, 'C1', 12000, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('complement', 'complement', '/ˈkɒmplɪment/', '[{"pos":"n./vt.","meaning":"补充；互补"}]', NULL, NULL, 'C1', 9500, '["cet6"]', '2026-09-14T20:11:14.624Z');
INSERT OR REPLACE INTO words (id, text, phonetic, definitions_json, audio_url, difficulty, cefr, frequency_rank, tags_json, created_at) VALUES ('consolidate', 'consolidate', '/kənˈsɒlɪdeɪt/', '[{"pos":"vt./vi.","meaning":"巩固；合并"}]', NULL, NULL, 'C1', 11800, '["cet6"]', '2026-09-14T20:11:14.624Z');
